### ISSUE TITLE
Prediction dimensions

### ISSUE THREAD

**Issue by Branikas** [milesial/Pytorch-UNet#114]
Hi everyone, happy new year!
I am testing the model on some different datasets, and I noticed that in one of them the prediction output has a different (higher) dimension than the input. For example when my input image is 480 x 320 pixel the output is the same, but when my inputs have size of 565 x 584, the output is 19 pixels bigger in each dimension.
Could it be because of the upsampling? (also scaling=1 for both the training and the prediction) 
Also i was training the model with patches of size 48 by 48 pixels.
Thanks

**Comment by milesial** [comment]
Yes it is because rounding errors makes so that the downscaling (max pool) and the upscaling don't match up for some values of width and height that are not divisible by 2 many times (like 565 and 584).

You could maybe rescale your end mask to your desired shape with bilinear interpolation at the end, or pad your input with zeros until you get a nice width and height that is divisible by 8 or 16.

**Comment by Branikas** [comment]
I figured, but wasn't sure if it was that. Thank you once more Milesial!

**Comment by talatccan** [comment]
> I figured, but wasn't sure if it was that. Thank you once more Milesial!

How you solved that? Can you explain? Thanks.
