### ISSUE TITLE
Use of ConvTransPose2d()

### ISSUE THREAD

**Issue by Kxy-Moriaty** [milesial/Pytorch-UNet#146]
https://github.com/milesial/Pytorch-UNet/blob/d685fe10ac571e28e818a9d8fb19013e3346ee5f/unet/unet_parts.py#L50

I don't quite get it, why should we use _in_channels//2_ but not _in_channels_.

**Comment by milesial** [comment]
I think you'll find anwers in #69

**Comment by Kxy-Moriaty** [comment]
I'm sorry I made it confused.
Let' say, the input tensor of first _Up_ is _x5_, which has 1024 channels. Then, in the _Up_ progress , if we want use ConvTranspose2d, shouldn't we use like:
`self.up = nn.ConvTranspose2d(1024, 516, ......)`
but in code ways ,we actually do it like:
`self.up = nn.ConvTranspose2d(516, 516,.....)`
So it confused me,the _x5_ actually has 1024 channels ,right?
Looking forwar your reply ,thank you so much.

**Comment by milesial** [comment]
Actually, x5 has 512 channels because I used bilinear upsampling and not the transposed conv, and you can read about that in #69 .

Now if we want to use the transposed convolutions and use them to halve the channels, then we may write
```
self.up = nn.ConvTranspose2d(in_channels, in_channels // 2, kernel_size=2, stride=2)
```
instead of 
```
self.up = nn.ConvTranspose2d(in_channels // 2, in_channels // 2, kernel_size=2, stride=2)
```
and modify `down4` (producing `x5`) so that `self.down4 = Down(512, 1024)` instead of `self.down4 = Down(512, 512)`

If that sounds clearer to you, please open a PR and I'll merge it.
