### ISSUE TITLE
RuntimeError: Class values must be smaller than num_classes.

### ISSUE THREAD

**Issue by viethoang303** [milesial/Pytorch-UNet#322]
Hi, everyone, t run code and got this error and the problem is:
F.one_hot(mask, classes).permute(0,3,1,2)
when max(mask) >= classes, this error will appear. I don't understand why people can use F.one_hot to encode mask.
Please help me

**Comment by chaymaaBOUSNAH** [comment]
Hi, me too I have this error, 
it's because the number of classes detected by one hot encoding is more than the number of classes that you have defined !
In my case it was just because the mask contains pixels of 0 and 255 so the one hot encoding made classes from 0 to 255 that's mean 256 classes !
I resolved this problem by divising all the pixel values by 255 in order to have only pixels of 0 and 1 (2 classes),
I hope this solution will be useful for you !

**Comment by viethoang303** [comment]
Before, I encode mask with one class, and now I set classes = 2 and it active. Thank you!!!
