### ISSUE TITLE
Why not use the PyTorch DataLoader?

### ISSUE THREAD

**Issue by Dr-Cube** [milesial/Pytorch-UNet#60]
I am a new learner of PyTorch. All the tutorial I have read taught me to customize `data.Dataset` class and use the `data.DataLoader` to read my own data set. They all come from `torch.utils.data`.

I am confused and curious about your style of reading dataset. Could please give me some guide of your way and code?

Thank u.

**Comment by milesial** [comment]
There is no reason not to implement a subclass of `data.Dataset`, it would be very easy. Back when this project was developped, the use of `utils.data` was not as widespread, or I didn't know about it, and a chain of operations on a python generator is a lightweight solution that allows to load in memory only the needed images.

**Comment by Dr-Cube** [comment]
Is there any chance that I could modify your code into a `data.Dataset` version, and how? Thx.
ps. I am using my own remote sensing dataset, not carvana.

**Comment by milesial** [comment]
My pipeline uses generators, so you would have to load all the images in memory in order to use the `Dataset` class and its `__getitem__` method.
You could then load some images into the GPU memory when needed.
Here is a simple tutorial to get you started https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

Feel free to experiment, and if it works you can submit a PR

**Comment by Dr-Cube** [comment]
ok, thank u. I will try to work on it.
