### ISSUE TITLE
Function Error

### ISSUE THREAD

**Issue by WxpHB** [milesial/Pytorch-UNet#62]
As we can see the function 'get_square(img,pos)' in utils.py(Line5)  file:
def get_square(img, pos):
    h=img.shape[0]
    if pos==0:
        return img[:,:h]
    else:
        return img[:,-h:]

To my knowledge，-1 represent the last element，and in this function -h represent the first element，so，':h' and '-h:'  represent the same thing. That is to say，img[:,:h] ==img[:,-h:], the outcome of the function get_square(img,pos) has nothing to do with parameter 'pos'.

**Comment by milesial** [comment]
-h does not represent the first element in the second dimension (where it is indexed). That would be true if it was the first dimension (the height) being cut, but here I cut along the width, because I assume that the width is larger than the height (see readme).

If your image is square (img.shape[0] == img.shape[1]), then what you're saying is true, and you don't need this function.

**Comment by WxpHB** [comment]
thank you.
