### ISSUE TITLE
unet_model in the code is a little different form the picture of the Unet

### ISSUE THREAD

**Issue by xiaochengfuhuo** [milesial/Pytorch-UNet#69]
thank you for your coding. today i want to recode your u-net,i fount that your code is different for the papaer -u-net. 

![Uploading KLFT$}`ANFY4RY4BN1TW(@A.png…]()
![}@Q %W)_8G$N@LCDO@7X15S](https://user-images.githubusercontent.com/23274737/63221622-51203600-c1ce-11e9-81cf-b5360f2393ee.png)

i do not konw  whether the goal is just easy coding or it works better.
looking forward your reply. thank you.

**Comment by xiaochengfuhuo** [comment]
![KLFT$}`ANFY4RY4BN1TW(@A](https://user-images.githubusercontent.com/23274737/63221669-f0ddc400-c1ce-11e9-9320-bd1bdf1251d6.png)

**Comment by milesial** [comment]
What do you find different ?

**Comment by xiaochengfuhuo** [comment]
for instance，in the last down layer（down4）,the out_channel is 512, but in unet is 1024  
![}@Q %W)_8G$N@LCDO@7X15S](https://user-images.githubusercontent.com/23274737/63224141-850d5280-c1f2-11e9-9711-e781c2feb32e.png)

**Comment by milesial** [comment]
Yes, I guess the right side of the image (the up convs) is modified to account for the use of bilinear upsampling :

https://github.com/milesial/Pytorch-UNet/blob/e2e46ce509382a45b1db4e1f639aeed568f6cb3e/unet/unet_parts.py#L56

This upsampling saves memory but is not a convolution so the number of channels is not changed (in the image for example, the first up-conv changes to channels from 1024 to 512).

Here you can see that all the number of output channels of the 'ups' are 2x smaller than in the image (256 vs 512, 128 vs 256, etc) : 
https://github.com/milesial/Pytorch-UNet/blob/e2e46ce509382a45b1db4e1f639aeed568f6cb3e/unet/unet_model.py#L15-L17

In practice, this transfers the change of the number of channels caused by up-conv (green arrow) to the double conv (blue arrows before the green arrow) : the output of the blue arrows is 2x smaller to account for the non-existent up-conv.

With this, we loose a convolution per up step (green arrow), but the output dimensions (channels) still match the needed dimensions for the next step.

All this is a result of adding bilinear upsampling to the model. You can choose to disable bilinear upsampling.

**Comment by xiaochengfuhuo** [comment]
oh! thank you very much. beacuse the bilinear upsampling can not 2x smaller the channels, you choose use double conv (blue arrows before the green arrow) to 2x smaller the channels. if we use nn.ConvTranspose2d ,we can 2x smaller the channels with the upsampling .
Do I have an exact understanding?

**Comment by milesial** [comment]
Yes you are correct !
