### ISSUE TITLE
The question about the function "get_square"  in “utils.py”

### ISSUE THREAD

**Issue by scmales** [milesial/Pytorch-UNet#73]
Why not resize the image into square?
The function "get_square" crops the image. Can it be good for results? Or bad?

**Comment by milesial** [comment]
Here the image is cropped into 2 squares so no data is lost. The resize operation could work but the image would be distorted, so I think the results would be worse, but I haven't tried it. I think that in order to get a high quality mask, the input image should be as high quality as possible, and not distorted.

**Comment by scmales** [comment]
Thank you！
